baseurl = "/"
languageCode = "pt-br"
title = "dobraga"
theme = "hugo-lithium"
googleAnalytics = "Ua-93877401-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Sobre"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/dobraga"
[[menu.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/douglas-martins-mendes-braga-904495b5/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml", "python"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    # https://www.iconfinder.com/iconsets/artificial-intelligence-6
    favicon = "iconfinder_ArtificialIntelligence25_2890583.png"

    [params.logo]
    url = "iconfinder_ArtificialIntelligence25_2890583.png"
    
    width = 50
    height = 50
    alt = "Logo"
