baseurl         = "/"
theme = "hugo-casper-two"
languageCode    = "pt-BR"
disqusShortname = ""
paginate        = 6
canonifyurls    = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  title       = "Douglas Braga"
  subtitle    = ""
  copyright   = "© 2020"

  description = ""
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = ""
  githubName = "dobraga"
  linkedinName = "douglas-braga-904495b5"
  mediumName = ""

  orgName = "dobraga"

  showSupport = true

  author = "Douglas Braga"
  authorAvatar = "https://media-exp1.licdn.com/dms/image/C4D03AQEHaQ5Kc2cAmw/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=yheJJ4d2GWxJdNd7ZB9vEGQ8KLbsVAdwEaODYoIILy8"
  authorLocation = "Rio de Janeiro"
  authorDescription = ""

  pageNotFoundTitle = "404 - Página não encontrada"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200
  
[[menu.main]]
  name = "Sobre"
  url = "about/"
  weight = 200

[[menu.main]]
  name = "Categorias"
  url = "/categories/"
  weight = 99

